steps:
# Use git clone
- id: Git clone
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/heyKim/public-skcc-2016-user']
# Image Build
- id: 'image build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/secret-bloom-244108/skcc-2016-user:$REVISION_ID', '.']
### Image Push
- id: 'image push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/secret-bloom-244108/skcc-2016-user:$REVISION_ID']
# Deployment Update(방법1)
- id: 'Deploy'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/user-deployment', 'skcc-2016-user-sha256=gcr.io/secret-bloom-244108/skcc-2016-user:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=lab02'
# Deployment Update(방법2)
- id: Deployment
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'user-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=lab02'
# Service Update(OPTIONAL)
- id: Service
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'user-service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=lab02'

# 빌드된 이미지를 저장하도록 image 필드 설정
images: ['gcr.io/secret-bloom-244108/skcc-2016-user']